package org.alealcruz.creditsbuilder.misc;

public class Disclaimer {
	
	private  static final String text_Disclaimer = 	   "*** Disclaimer of Warranty ***\n\n"
			+ "COVERED SOFTWARE IS PROVIDED UNDER THIS LICENSE ON AN\n"
			+ "\"AS IS\" BASIS, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED\n"
			+ "OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES THAT THE\n"
			+ "COVERED SOFTWARE IS FREE OF DEFECTS, MERCHANTABLE, FIT FOR A\n"
			+ "PARTICULAR PURPOSE OR NON-INFRINGING. THE ENTIRE RISK AS TO THE\n"
			+ "QUALITY AND PERFORMANCE OF THE COVERED SOFTWARE IS WITH YOU.\n"
			+ "SHOULD ANY COVERED SOFTWARE PROVE DEFECTIVE IN ANY RESPECT, YOU\n"
			+ "(NOT THE INITIAL DEVELOPER OR ANY OTHER CONTRIBUTOR) ASSUME THE\n"
			+ "COST OF ANY NECESSARY SERVICING, REPAIR OR CORRECTION.\n"
			+ "THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS\n"
			+ "LICENSE. NO USE OF ANY COVERED SOFTWARE IS AUTHORIZED HEREUNDER\n"
			+ "EXCEPT UNDER THIS DISCLAIMER.\n\n"
			+ "LICENSE: CC-BY-SA\n"
			+ "AUTHOR: Alejandro Leal Cruz\n"
			+ "First version: 20220323-alpha1.0\n"
			+ "Current version: 20220831-alpha1.0\n\n";
	
	public static String getDisclaimerText() {
		return text_Disclaimer;
	}

}
